### ISSUE TITLE
Request for JDK-8u202

### ISSUE THREAD

**Issue by koolkunz** [portapps/oracle-jdk-portable#20]
Can you please make a build for JDK 8u202 as that is the last version of JDK 8 that can be used freely commercially. All releases after that require an oracle license for commercial usage.

It can be found here: https://www.oracle.com/java/technologies/javase/javase8-archive-downloads.html

**Comment by koolkunz** [comment]
Or else can you share how you create the '\app' directory from original java se setup so that I can just replicate it for 8u202

**Comment by koolkunz** [comment]
Also I wanted to ask one more question, hope you dont mind me asking it here, does the oracle-jdk-portable.exe only set JAVA_HOME environment variable or does it do anything else also?

**Comment by crazy-max** [comment]
Latest is 8u251 ans is alreay available: https://portapps.io/app/oracle-jdk-portable/

> Also I wanted to ask one more question, hope you dont mind me asking it here, does the oracle-jdk-portable.exe only set JAVA_HOME environment variable or does it do anything else also?

Only set JAVA_HOME environment variable yes.
