### ISSUE TITLE
Please add src.zip

### ISSUE THREAD

**Issue by visualwind** [portapps/oracle-jdk-portable#5]
#### Steps to reproduce this issue

1.
2.
3.

#### Expected behaviour

> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :

**Operating system (ex. Windows 10 Pro 64 bits)** :

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

**Comment by crazy-max** [comment]
@visualwind Already available in `./app/lib/src.zip`

**Comment by visualwind** [comment]
> @visualwind Already available in `./app/lib/src.zip`

You didnt add src.zip in the recent JDK8u241-12.  It is 20.2MB.
People, who use jdk, usually need src.zip.  I downloaded the official installer to get that

**Comment by crazy-max** [comment]
@visualwind Should be fixed now in latest 8u release.
